site_name: Komodor 
strict: true
site_url: ""
use_directory_urls: false
theme:
  name: material
  palette:
    primary: indigo 
markdown_extensions:
- codehilite
- admonition
- toc:
    permalink: true
nav:
  - Welcome: index.md