site_name: Komodor 
strict: true
site_url: ""
use_directory_urls: false
theme:
  name: material
  palette:
    primary: indigo 
markdown_extensions:
- codehilite
- admonition
- toc:
    permalink: true
nav:
  - Welcome: index.md
  - Annotations: Annotations.md
  - Config-Changes: config-changes.md
  - Integrations:
    - Datadog: Integrations/Datadog.md
    - Datadog-Webhook: Integrations/datadog-webhook.md
    - Grafana: Integrations/Grafana.md
    - LaunchDarkly: Integrations/LaunchDarkly.md
    - PagerDuty: Integrations/PagerDuty.md
    - Sentry: Integrations/Sentry.md
  - Source-Control: komodor-source-control.md
  - Sensitive-Information-Redaction: Sensitive-Information-Redaction.md